### ISSUE TITLE
not an issue but

### ISSUE THREAD

**Issue by saffue** [YorickBM/TwerkingCrops#3]
any chance on this getting a 1.19 update, it does work if you ignore the closing errors lol

Error occurred while disabling Twerking-Crops v11.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getBlockAt(org.bukkit.Location)" because the return value of "org.bukkit.Location.getWorld()" is null
        at org.bukkit.Location.getBlock(Location.java:133) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at Spigot.TwerkingCrops.ToolBox.locationToString(ToolBox.java:241) ~[Twerking-Crops.jar:?]
        at Spigot.TwerkingCrops.CustomTimer.SeedType.toString(SeedType.java:32) ~[Twerking-Crops.jar:?]
        at Spigot.TwerkingCrops.ToolBox.lambda$SaveCropsToConfig$0(ToolBox.java:78) ~[Twerking-Crops.jar:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at Spigot.TwerkingCrops.ToolBox.SaveCropsToConfig(ToolBox.java:78) ~[Twerking-Crops.jar:?]
        at Spigot.TwerkingCrops.Core.onDisable(Core.java:158) ~[Twerking-Crops.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:556) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:499) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:943) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:808) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-235]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by YorickBM** [comment]
There will be one final update, that will allow for manual further adding of new crops if released by minecraft.
Sadly this update has been put on the back burner due to my studies. Hopefully it can be released soon. This will also be patched then.

**Comment by saffue** [comment]
no worrys thank you

**Comment by floraider2** [comment]
do you still plan on updating?

**Comment by YorickBM** [comment]
Hey, currently i do not have the time to develop the plugin and test it propperly.
As it is hard to keep up with the large cycle of updates minecraft is giving out. 
They do not make each new crop/bonemealable item implemented in a way that clear or structured.
This repo can of course be forked and adapted by someone else.
